export const UPDATE_APPOINTMENT_TYPE = 'UPDATE_APPOINTMENT_TYPE';
export const UPDATE_APPOINTMENT_TIME = 'UPDATE_APPOINTMENT_TIME';
export const UPDATE_APPOINTMENT_DATE = 'UPDATE_APPOINTMENT_DATE';
export const UPDATE_FORM_VALS = 'UPDATE_FORM_VALS';
export const CLEAR_VALS = 'CLEAR_VALS';